### ISSUE TITLE
snap (and probably other tools) - failing task is hidden in CI

### ISSUE THREAD

**Issue by shlomitc** [wix-incubator/ui-autotools#205]
when a task like `snap` fails, the error hides inside the logs and doesn't focus the exact cause.

for example, this is how an error currently looks like
![image](https://user-images.githubusercontent.com/6093192/49454182-5169d400-f7ed-11e8-8c16-2f8350f489c2.png)

while it's hidden here
![image](https://user-images.githubusercontent.com/6093192/49454255-752d1a00-f7ed-11e8-86cc-159ec660286b.png)

http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=1216524&buildTypeId=FedInfra_WixUi_Packages_WixUiCode&tab=buildLog&_focus=4251#_state=291

**Comment by JoMarton** [comment]
We're on it
