### ISSUE TITLE
autotools-snap - Issues with wix-style-react

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/ui-autotools#216]
## Logs don't show that no files were "snapped"

The output I see it:
```
Building base files...
Generating snapshots...
Sending snapshots to Applitools...
```

That makes me think that everything went well, while actually no snapshot was even created.

### exportName

WSR components mostly export `default` , not a named variable.
Can that be supported?

### baseStylePath

most WSR component use Sass, so there is a css raw file if needed.
is that supported?

## Branch support

I saw that branchName has always a ‘master’ suffix

**Comment by Zombiefruit** [comment]
Regarding support default exports, it's not a huge deal to support this, we just need to add another option to the `exportedFrom` section.

Output should definitely be improved when no tests are present. 

Supporting anything other than Stylable is a big task as currently a large part of the flow relies on `stylable-webpack-extension`.
